# Generated by Django 4.2.4 on 2023-09-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0004_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
