# Generated by Django 4.2.4 on 2023-09-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0009_rename_prescription_required_cartitem_requires_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
