# Generated by Django 4.2.2 on 2023-09-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0010_alter_medicine_sell_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name_plural': 'Medicines'},
        ),
        migrations.AlterField(
            model_name='medicine',
            name='batch_no',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
