# Generated by Django 4.2.2 on 2023-10-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0011_alter_medicine_options_alter_medicine_batch_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='prescription',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
    ]
