# Generated by Django 4.2.2 on 2023-10-12 10:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0012_cartitem_prescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.PositiveIntegerField(help_text='Alert when stock falls below this quantity', validators=[django.core.validators.MinValueValidator(1)])),
                ('last_triggered', models.DateTimeField(auto_now=True, help_text='Timestamp when the alert was last triggered')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logi.medicine')),
            ],
            options={
                'verbose_name_plural': 'Medicine Stock Alerts',
            },
        ),
    ]
