# Generated by Django 4.2.2 on 2023-10-19 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0014_prescription_alter_cartitem_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='user',
        ),
        migrations.AddField(
            model_name='prescription',
            name='cart',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='logi.cart'),
            preserve_default=False,
        ),
    ]
