# Generated by Django 4.2.2 on 2023-10-19 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0015_rename_uploaded_at_prescription_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logi.cart'),
        ),
    ]
