# Generated by Django 4.2.2 on 2024-01-16 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0019_customer_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='razorpaypayment',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='RazorpayPayment',
        ),
    ]
