# Generated by Django 4.2.5 on 2024-02-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0020_remove_orderitem_medicine_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Company_id', models.AutoField(primary_key=True, serialize=False)),
                ('Company_Name', models.CharField(max_length=100, unique=True)),
                ('License_No', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=225)),
                ('Contact_no', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=100)),
                ('Description', models.TextField()),
                ('Added_on', models.DateField(auto_now_add=True)),
                ('Status', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_medrep',
            field=models.BooleanField(default=False),
        ),
    ]
