# Generated by Django 4.2.5 on 2024-02-06 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0021_company_user_is_medrep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='company_id',
        ),
    ]
