# Generated by Django 4.2.5 on 2024-02-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0022_remove_medicine_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='company_id',
            field=models.CharField(default='sun', max_length=255),
            preserve_default=False,
        ),
    ]
