# Generated by Django 4.2.5 on 2024-02-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0023_medicine_company_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_medrep',
        ),
    ]
