# Generated by Django 4.2.5 on 2024-02-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0024_delete_company_remove_user_is_medrep'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_medical_representative',
            field=models.BooleanField(default=False),
        ),
    ]
