# Generated by Django 4.2.5 on 2024-02-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0025_user_is_medical_representative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_medical_representative',
        ),
    ]
