# Generated by Django 4.2.5 on 2024-02-07 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0026_remove_user_is_medical_representative'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRepresentative',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_medical_representative',
            field=models.BooleanField(default=False),
        ),
    ]
