# Generated by Django 4.2.2 on 2024-02-09 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0027_medicalrepresentative_user_is_medical_representative'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='description',
            new_name='how_it_works',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='company_id',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='buy_price',
            new_name='mrp',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='medicine_type',
            new_name='type_of_sell',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='batch_no',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='exp_date',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='mfg_date',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='sell_price',
        ),
        migrations.AddField(
            model_name='medicine',
            name='action_class',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='alternate_medicines',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='chemical_class',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='habit_forming',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='how_to_use',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='prescription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicine',
            name='salt',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='side_effects',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='medicine',
            name='therapeutic_class',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='uses',
            field=models.TextField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='wholesale_price',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
