# Generated by Django 4.2.2 on 2024-02-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0028_rename_description_medicine_how_it_works_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='mrp',
            new_name='buy_price',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='manufacturer',
            new_name='company_id',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='how_it_works',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='type_of_sell',
            new_name='medicine_type',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='action_class',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='alternate_medicines',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='chemical_class',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='habit_forming',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='how_to_use',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='prescription',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='side_effects',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='status',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='therapeutic_class',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='uses',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='wholesale_price',
        ),
        migrations.AddField(
            model_name='medicine',
            name='exp_date',
            field=models.DateField(default='2025-12-31'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='mfg_date',
            field=models.DateField(default='2023-12-31'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
