# Generated by Django 4.2.2 on 2024-02-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0032_remove_medicine_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_image',
            field=models.ImageField(blank=True, null=True, upload_to='medicine_images/'),
        ),
    ]
