# Generated by Django 4.2.2 on 2024-02-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0033_alter_medicine_medicine_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('num', models.CharField(max_length=255)),
            ],
        ),
    ]
