# Generated by Django 4.2.2 on 2024-02-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0034_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
