# Generated by Django 4.2.2 on 2024-02-19 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0036_rename_id_demo_medical_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='medicine_id',
            new_name='id',
        ),
    ]
