# Generated by Django 4.2.2 on 2024-02-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0037_rename_medicine_id_medicine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='how_it_works',
            field=models.TextField(blank=True, null=True),
        ),
    ]
