# Generated by Django 4.2.2 on 2024-02-19 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0038_alter_medicine_how_it_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='alternate_medicines',
            field=models.TextField(blank=True, null=True),
        ),
    ]
