# Generated by Django 4.2.2 on 2024-02-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0039_alter_medicine_alternate_medicines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='medicine_name',
            field=models.CharField(max_length=255),
        ),
    ]
