# Generated by Django 4.2.2 on 2024-02-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0041_alter_medicine_how_to_use_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='id',
            new_name='medicine_id',
        ),
    ]
