# Generated by Django 4.2.5 on 2024-02-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0042_rename_id_medicine_medicine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrepresentative',
            name='total_quantity_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicalrepresentative',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
