# Generated by Django 4.2.5 on 2024-02-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0043_medicalrepresentative_total_quantity_sold_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrepresentative',
            name='total_quantity_sold',
        ),
        migrations.RemoveField(
            model_name='medicalrepresentative',
            name='total_sales',
        ),
    ]
