# Generated by Django 4.2.5 on 2024-03-21 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0044_remove_medicalrepresentative_total_quantity_sold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_medical_representative',
        ),
        migrations.AddField(
            model_name='user',
            name='is_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MedicalRepresentative',
        ),
    ]
