# Generated by Django 4.2.5 on 2024-03-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0033_remove_deliverystatusupdate_order_and_more'),
        ('logi', '0045_deliveryperson_remove_user_is_medical_representative_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_delivery',
        ),
        migrations.DeleteModel(
            name='DeliveryPerson',
        ),
    ]
