# Generated by Django 4.2.5 on 2024-03-22 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0035_delete_delivery'),
        ('logi', '0047_user_is_delivery_deliveryperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_delivery',
        ),
        migrations.DeleteModel(
            name='DeliveryPerson',
        ),
    ]
