# Generated by Django 4.2.5 on 2024-03-22 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0048_remove_user_is_delivery_delete_deliveryperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=20)),
                ('vehicle_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_delivery_person',
            field=models.BooleanField(default=False),
        ),
    ]
