# Generated by Django 4.2.2 on 2024-01-15 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0017_prescription_is_verified_alter_prescription_cart_and_more'),
        ('main_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='medicines',
            field=models.ManyToManyField(through='main_project.OrderItem', to='logi.medicine'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logi.medicine'),
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
