# Generated by Django 4.2.5 on 2024-01-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0002_alter_order_medicines_alter_orderitem_medicine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
