# Generated by Django 4.2.5 on 2024-01-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0003_order_payment_url_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.AddField(
            model_name='order',
            name='short_url',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
