# Generated by Django 4.2.5 on 2024-01-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0004_remove_order_razorpay_order_id_order_short_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_url',
        ),
        migrations.RemoveField(
            model_name='order',
            name='short_url',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(default=45, max_length=255),
            preserve_default=False,
        ),
    ]
