# Generated by Django 4.2.5 on 2024-01-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0005_remove_order_payment_url_remove_order_short_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
