# Generated by Django 4.2.5 on 2024-01-31 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0020_remove_orderitem_medicine_remove_orderitem_order_and_more'),
        ('main_project', '0009_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cart',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='logi.cart'),
            preserve_default=False,
        ),
    ]
