# Generated by Django 4.2.5 on 2024-01-31 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0011_orderstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
