# Generated by Django 4.2.5 on 2024-02-05 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0014_purchaseorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='address',
        ),
    ]
