# Generated by Django 4.2.5 on 2024-02-07 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0016_medicalrepresentative'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalRepresentative',
        ),
    ]
