# Generated by Django 4.2.5 on 2024-02-28 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0043_medicalrepresentative_total_quantity_sold_and_more'),
        ('main_project', '0017_delete_medicalrepresentative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logi.customer')),
                ('medical_representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logi.medicalrepresentative')),
                ('medicines_to_introduce', models.ManyToManyField(related_name='introduced_in_appointments', to='logi.medicine')),
            ],
        ),
    ]
