# Generated by Django 4.2.5 on 2024-02-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0018_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_sale',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
