# Generated by Django 4.2.5 on 2024-03-04 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0044_remove_medicalrepresentative_total_quantity_sold_and_more'),
        ('main_project', '0022_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logi.medicine')),
            ],
            options={
                'unique_together': {('manufacturer', 'medicine')},
            },
        ),
    ]
