# Generated by Django 4.2.5 on 2024-03-18 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0044_remove_medicalrepresentative_total_quantity_sold_and_more'),
        ('main_project', '0026_alter_orderitem_cart_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logi.prescription'),
        ),
    ]
