# Generated by Django 4.2.5 on 2024-03-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0027_order_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
