# Generated by Django 4.2.5 on 2024-03-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0029_order_is_delivered_order_order_number_deliveryperson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryperson',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.DeleteModel(
            name='DeliveryAssignment',
        ),
        migrations.DeleteModel(
            name='DeliveryPerson',
        ),
    ]
