# Generated by Django 4.2.5 on 2024-03-21 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0045_deliveryperson_remove_user_is_medical_representative_and_more'),
        ('main_project', '0031_deliverystatusupdate_deliveryperson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryassignment',
            name='delivery_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logi.deliveryperson'),
        ),
        migrations.DeleteModel(
            name='DeliveryPerson',
        ),
    ]
