# Generated by Django 4.2.5 on 2024-03-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0032_alter_deliveryassignment_delivery_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverystatusupdate',
            name='order',
        ),
        migrations.DeleteModel(
            name='DeliveryAssignment',
        ),
        migrations.DeleteModel(
            name='DeliveryStatusUpdate',
        ),
    ]
