# Generated by Django 4.2.5 on 2024-03-21 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0047_user_is_delivery_deliveryperson'),
        ('main_project', '0033_remove_deliverystatusupdate_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_address', models.CharField(max_length=255)),
                ('delivery_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logi.deliveryperson')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_project.order')),
            ],
        ),
    ]
