# Generated by Django 4.2.5 on 2024-03-22 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0034_delivery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
