# Generated by Django 4.2.5 on 2024-03-22 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0049_deliveryperson_user_is_delivery_person'),
        ('main_project', '0035_delete_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('delivery_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logi.deliveryperson')),
            ],
        ),
    ]
