# Generated by Django 4.2.5 on 2024-03-22 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0049_deliveryperson_user_is_delivery_person'),
        ('main_project', '0036_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_delivery_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logi.deliveryperson'),
        ),
    ]
