# Generated by Django 4.2.5 on 2024-03-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_project', '0037_order_assigned_delivery_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_delivery_person',
            field=models.BooleanField(default=False),
        ),
    ]
